default:
  workspace: shared

stages:
- Build
- Test

jobs:
- name: Run tests
  stage: Build
  image: alpine
  services:
  - redis:alpine
  script:
  - echo Hello

- name: Sleep
  stage: Build
  image: alpine
  workspace: false
  script:
  - sleep 10
  when: manual

- name: Wake up
  stage: Build
  image: alpine
  script:
  - echo Hello

- name: Sleep again
  stage: Build
  image: alpine
  script:
  - sleep 10
  depends_on:
    - Sleep

- name: Sleep more
  stage: Test
  image: alpine
  script:
  - sleep 10
  depends_on:
    - Run tests

- name: Say bye!
  stage: Test
  image: alpine
  script:
  - sleep 10
  - echo Bye
