default:
  workspace: shared

stages:
  - persist_workspace
  - attach_workspace
  - attach_workspace_again

jobs:
  - name: Persist
    stage: persist_workspace
    image: node:14-alpine
    script:
      - ls -la /build/hoanglm-2435/laravel-nuxt-project
      - mkdir -p /workspace/pages
      - mv demo-app-client/pages/* /workspace/pages
      - mv demo-app-client/static/* /workspace/static
      - ls -la /workspace
    cache:
      - key:
          files:
            - demo-app-client/yarn.lock
            - demo-app-client/package.json
        paths:
          - demo-app-client/static
    workspace:
      - persist:
          root: /workspace
          paths:
            - pages
            - static

  - name: Attach
    stage: attach_workspace
    image: node:14-alpine
    script:
      - pwd
      - ls -la /build/hoanglm-2435/laravel-nuxt-project
      - ls -la /workspace/pages
      - cat /workspace/pages/index.vue
      - rm -rf /workspace/pages/index.vue
    workspace:
      - attach: /workspace/pages

  - name: Attach again
    stage: attach_workspace_again
    image: node:14-alpine
    script:
      - ls -la /workspace/pages
    workspace:
      - attach: /workspace/pages
