stages:
  - Install

jobs:
  - name: Composer Install
    stage: Install
    use: Composer Install
    with: 
      dockerImage: ghcr.io/sun-asterisk-research/php-dev:7.4.30-alpine3.15
      appDir: api
      cacheFile: api/composer.lock
      vendorDir: api/vendor
