workspace: false

stages:
  - build
  - test
  - deploy

jobs:
  - name: Job 1
    stage: build
    image: node:12-alpine
    allow_failure: true
    services:
      - redis:alpine
    before_script:
      - echo before_script
    script:
      - ls -la
      - echo "Build title should take only subject from commit message"
    after_script:
      - echo "Build title should take only subject from commit message"
    artifacts:
      paths:
      - demo-app-server/app/Http
      expires_in: 3 days
    release:
      environment: test
      url: https://htt.com
  
  - name: Job 2
    stage: build
    image: node:12-alpine
    allow_failure: false
    services:
      - redis:alpine
    before_script:
      - echo before_script
    script:
      - ls -la
      - echo "Build title should take only subject from commit message"
    after_script:
      - echo "Build title should take only subject from commit message"
    artifacts:
      paths:
      - demo-app-server/app/Http
      expires_in: 3 days
    release:
      environment: test
      url: https://htt.com

  - name: Allow failed job
    stage: test
    image: node:12-alpine
    allow_failure: true
    script:
      - sleep 5
      - exit 1
      
  - name: Job 3
    stage: test
    image: node:12-alpine
    release:
      environment: production
      url: https://htt22.com
    script:
      - sleep 5
      - echo done
  - name: Job 4
    stage: deploy
    image: node:12-alpine
    release:
      environment: production
      url: https://htt.com
    script:
      - sleep 5
      - echo done
  - name: Disallow failure
    stage: deploy
    image: node:12-alpine
    release:
      environment: production
      url: https://htt.com
    script:
      - sleep 5
      - exit 1