default:
  workspace: shared

checkout:
  depth: 3

stages:
  - Install
  - Test
  - Build
  - Analysis

jobs:
  - name: Yarn Install
    stage: Install
    image: node:14-alpine
    before_script:
      - yarn config set network-timeout 300000
    script:
      - yarn
    cache:
      - key:
          files:
            - web/yarn.lock
        paths:
          - web/node_modules
    workspace:
      - persist:
          root: web
          paths:
            - node_modules


  - name: Composer Install
    stage: Install
    image: ghcr.io/sun-asterisk-research/php-dev:7.4.30-alpine3.15
    script:
      - composer install -d api
    cache:
      - key:
          files:
            - api/composer.lock
        paths:
          - api/vendor
    workspace:
      - persist:
          root: api
          paths:
            - vendor

  - name: ESLint
    stage: Test
    image: node:14-alpine
    script:
      - yarn lint --max-warnings 0
    workspace:
      - attach: web/node_modules

  - name: PHP CodeSniffer
    stage: Test
    image: sunasteriskrnd/php-workspace:7.4
    script:
      - composer sniff -d api
    workspace:
      - attach: api/vendor

  - name: Composer Sniffer
    stage: Test
    image: ghcr.io/sun-asterisk-research/php-dev:7.4.30-alpine3.15
    script:
      - composer sniff -d api
