default:
  workspace: shared

stages:
  - Install

jobs:
  - name: Yarn Install
    stage: Install
    image: node:14-alpine
    before_script:
    - yarn config set network-timeout 300000
    script:
    - yarn
    cache:
    - key:
        files:
        - demo-app-client/yarn.lock
      paths:
      - demo-app-client/node_modules

  - name: Composer Install
    stage: Install
    image: sunasteriskrnd/php-workspace:7.4
    script:
    - composer install -d demo-app-server
    cache:
    - key:
        files:
        - demo-app-server/composer.lock
      paths:
      - demo-app-server/vendor
