default:
  workspace: shared

stages:
- Build

jobs:
- name: Sleep
  stage: Build
  image: alpine
  script:
  - sleep 10

- name: Wake up
  stage: Build
  image: alpine
  script:
  - echo Hello

- name: Sleep again
  stage: Build
  image: alpine
  script:
  - sleep 10
  depends_on:
    - Sleep

- name: Sleep more
  stage: Build
  image: alpine
  script:
  - sleep 10
  depends_on:
    - Anonymous job
