default:
  workspace: shared

checkout:
  depth: 3

stages:
  - Install
  - Test
  - Build
  - Analysis

jobs:
  - name: Yarn Install
    stage: Install
    image: node:14-alpine
    before_script:
      - yarn config set network-timeout 300000
    script:
      - yarn install
      - ls -la web
      - mkdir -p /workspace/web/node_modules
      - cp -r web/node_modules/* /workspace/web/node_modules
      - ls -la /workspace/web/node_modules
    cache:
      - key:
          files:
            - web/yarn.lock
        paths:
          - web/node_modules
    workspace:
      - persist:
          root: /workspace
          paths:
            - web
