stages:
  - a
jobs:
  - name: aaa
    image: alpine
    stage: a
    script:
      - echo "test"
      - apk add curl
      - sleep 60
      - curl -X GET "elastic:9200/_cat/nodes?v&pretty"
    services:
      - name: elastic
        image: elasticsearch:7.12.1
        environment:
        - cluster.name=docker-cluster
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
