version: 2.1

orbs:
  node: circleci/node@4.7.0

references:
  workspace_root: &workspace_root
    /tmp/workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

workflows:
  test-build:
    jobs:
      - yarn_install
      - yarn_install_again
      
jobs:
  yarn_install:
    executor:
      name: node/default
      tag: '14.17.3'
    steps:
      - *attach_workspace
      - checkout
      - run: 
          name: "Lint JS assets"
          command: |
            set -exu
            mkdir -p /tmp/workspace/pages/test
            mv demo-app-client/pages/* /tmp/workspace/pages/test
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - pages
  yarn_install_again:
    executor:
      name: node/default
      tag: '14.17.3'
    steps:
      - attach_workspace:
          at: /tmp/workspace/pages/test
      - checkout
      - run: 
          name: "Lint JS assets"
          command: |
            ls -la /tmp/workspace/pages/test
            cat /tmp/workspace/pages/test/index.vue
    