version: 2.1

orbs:
  node: circleci/node@4.7.0

references:
  workspace_root: &workspace_root
    /tmp/workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

workflows:
  test-build:
    jobs:
      - persirt_data_to_workspace
      - attach_data_from_workspace:
          requires:
            - persirt_data_to_workspace
      - attach_workspace_again: 
          requires:
            - persirt_data_to_workspace
jobs:
  persirt_data_to_workspace:
    executor:
      name: node/default
      tag: '14.17.3'
    steps:
      - attach_workspace:
          at: /
      - checkout
      - run: 
          name: "Persist data to workspace"
          command: |
            set -exu
            mkdir -p /tmp/workspace/pages
            mv demo-app-client/pages/* /tmp/workspace/pages
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - pages
  attach_data_from_workspace:
    executor:
      name: node/default
      tag: '14.17.3'
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run: 
          name: "Attach data from workspace"
          command: |
            ls -la /tmp/workspace/pages
            cat /tmp/workspace/pages/index.vue
            rm -rf /tmp/workspace/pages/index.vue
  attach_workspace_again:
    executor:
      name: node/default
      tag: '14.17.3'
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run: 
          name: "Attach data from workspace again"
          command: |
            ls -la /tmp/workspace/pages
            cat /tmp/workspace/pages/index.vue
    