version: 2.1

orbs:
  node: circleci/node@4.7.0

references:
  workspace_root: &workspace_root
    /tmp/workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

workflows:
  test-build:
    jobs:
      - yarn_install
      - yarn_install_again:
          requires:
            - yarn_install

jobs:
  yarn_install:
    executor:
      name: node/default
      tag: '14.17.3'
    steps:
      - attach_workspace:
          at: /
      - checkout
      - run: 
          name: "Lint JS"
          command: |
            set -exu
            mkdir -p /tmp/workspace/pages
            mv demo-app-client/pages/* /tmp/workspace/pages
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - pages
  yarn_install_again:
    executor:
      name: node/default
      tag: '14.17.3'
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run: 
          name: "Lint JS assets"
          command: |
            ls -la /tmp/workspace/pages
            cat /tmp/workspace/pages/index.vue
    