on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      tag:
        required: true
        type: string
      unique_tag_suffix:
        required: true
        type: string
      app_url:
        required: true
        type: string

env:
  HARBOR_REGISTRY: ${{ secrets.HARBOR_REGISTRY }}
  HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
  HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}

jobs:
  build:
    environment: 
      name: ${{ inputs.environment }}
      url: https://github.com
    runs-on: ubuntu-latest
    container: docker:20.10.17
    services:
      dind:
        image: docker:20.10.17-dind
    env:
      TAG: ${{ inputs.tag }}
      APP_URL: ${{ inputs.app_url }}
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to ${{ inputs.environment }}
        run: |
          echo "$HARBOR_PASSWORD" "$HARBOR_REGISTRY" "$HARBOR_PASSWORD"
