name: Demo Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  staging:
    uses: ./.github/workflows/build.yml
    with:
      environment: staging
      tag: develop
      unique_tag_suffix: -stg
      app_url: https://atlas-staging.sun-asterisk.vn
    secrets: inherit

  production:
    uses: ./.github/workflows/build.yml
    with:
      environment: production
      tag: stable
      unique_tag_suffix: -prod
      app_url: https://atlas.sun-asterisk.vn
    secrets: inherit
