name: Demo Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - env: staging
            ref: develop
            tag: develop
            suffix: -stg
            url: https://atlas-staging.sun-asterisk.vn
          - env: production
            ref: master
            tag: stable
            suffix: -prod
            url: https://atlas.sun-asterisk.vn
    if: $GITHUB_REF_NAME == 'master' && $GITHUB_EVENT_NAME == 'push'
    runs-on: ubuntu-latest
    container: docker:20.10.17
    env:
      TAG: ${{ matrix.tag }}
      UNIQUE_TAG_SUFFIX: ${{ matrix.suffix }}
      APP_URL: ${{ matrix.url }}
    services:
      dind:
        image: docker:20.10.17-dind
    steps:
      - uses: actions/checkout@v3

      - name: Deploy ${{ matrix.env }}
        run: |
          echo ${{ matrix.env }} ${{ matrix.tag }} ${{ matrix.suffix }} ${{ matrix.url }} ${{ matrix.ref }}
